### ISSUE TITLE
TODO: Tier 1 kernel implementations

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#120]
List of kernel to be implemented in CLIc, based from the pyclesperanto-prototype list.

If the link return a 404 error, it means that the kernel is not yet available for the [clespernanto-kernel](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels) branch. See [this issue](https://github.com/clEsperanto/clij-opencl-kernels/issues/17) for more info.

Please create a branch or a PR draft for the development of new kernel so that we can see those which are under development.

Kernels with a :question: next to them, means we do not know yet how relevant it is to keep them.
Kernels with a :exclamation: next to them, means we need to update their `.cl` code before implementation.

## Tiers 1

- [X] [absolute](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/absolute.cl)
- [X] [add_image_and_scalar](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/add_image_and_scalar.cl)
- [X] [add_images_weighted](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/add_images_weighted.cl)
- [ ] [average_distance_of_n_far_off_distances](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/average_distance_of_n_far_off_distances.cl) :question:
- [ ] [average_distance_of_n_nearest_distances](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/average_distance_of_n_nearest_distances.cl) :question:
- [ ] [average_distance_of_n_shortest_distances](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/average_distance_of_n_shortest_distances.cl) :question:
- [ ] [average_distance_of_touching_neighbors](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/average_distance_of_touching_neighbors.cl) :question:
- [X] [binary_and](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/binary_and.cl)
- [x] [binary_edge_detection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/binary_edge_detection.cl)
- [X] [binary_not](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/binary_not.cl)
- [X] [binary_or](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/binary_or.cl)
- [X] [binary_subtract](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/binary_subtract.cl)
- [X] [binary_xor](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/binary_xor.cl)
- [x] [convolve](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/convolve.cl)
- [X] [copy](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/copy.cl)
- [x] [copy_horizontal_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/copy_horizontal_slice.cl)
- [x] [copy_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/copy_slice.cl)
- [x] [copy_vertical_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/copy_vertical_slice.cl)
- [x] [count_touching_neighbors](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/count_touching_neighbors.cl)
- [x] [crop](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/crop.cl)
- [x] [cubic_root](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/cubic_root.cl)
- [x] [detect_label_edges](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/detect_label_edges.cl)
- [X] [detect_maxima](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/detect_maxima.cl)
- [x] [detect_minima](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/detect_minima.cl)
- [x] [dilate_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/dilate_box.cl)
- [ ] [dilate_box_slice_by_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/dilate_box_slice_by_slice.cl)
- [X] [dilate_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/dilate_sphere.cl)
- [ ] [dilate_sphere_slice_by_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/dilate_sphere_slice_by_slice.cl) :question:
- [X] [divide_images](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/divide_images.cl)
- [x] #158
- [ ] [downsample_slice_by_slice_half_median](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/downsample_slice_by_slice_half_median.cl) :question:
- [ ] [draw_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/draw_box.cl) :question:
- [ ] [draw_line](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/draw_line.cl) :question:
- [ ] [draw_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/draw_sphere.cl) :question:
- [X] [equal](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/equal.cl)
- [x] [equal_constant](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/equal_constant.cl)
- [x] [erode_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/erode_box.cl)
- [ ] [erode_box_slice_by_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/erode_box_slice_by_slice.cl) :question:
- [X] [erode_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/erode_sphere.cl)
- [ ] [erode_sphere_slice_by_slice](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/erode_sphere_slice_by_slice.cl)
- [X] [execute_separable_kernel](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/execute_separable_kernel.cl)
- [x] [exponential](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/exponential.cl)
- [x] [flip](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/flip.cl)
- [X] [gaussian_blur](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/gaussian_blur.cl)
- [ ] [generate_angle_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_angle_matrix.cl) :question:
- [x] [generate_binary_overlap_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_binary_overlap_matrix.cl)
- [x] [generate_distance_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_distance_matrix.cl)
- [x] [generate_touch_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_touch_matrix.cl)
- [X] [gradient_x](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/gradient_x.cl)
- [X] [gradient_y](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/gradient_y.cl)
- [X] [gradient_z](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/gradient_z.cl)
- [X] [greater](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/greater.cl)
- [X] [greater_constant](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/greater_constant.cl)
- [X] [greater_or_equal](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/greater_or_equal.cl)
- [X] [greater_or_equal_constant](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/greater_or_equal_constant.cl)
- [x] [hessian_eigenvalues](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/hessian_eigenvalues.cl)
- [x] [laplace_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/laplace_box.cl)
- [x] [laplace_diamond](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/laplace_diamond.cl)
- [x] [logarithm](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/logarithm.cl)
- [X] [mask](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mask.cl)
- [x] [mask_label](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mask_label.cl)
- [X] [maximum_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_box.cl)
- [ ] [maximum_distance_of_n_shortest_distances](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_distance_of_n_shortest_distances.cl) :question:
- [ ] [maximum_distance_of_touching_neighbors](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_distance_of_touching_neighbors.cl) :question:
- [x] [maximum_image_and_scalar](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_image_and_scalar.cl)
- [x] [maximum_images](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_images.cl)
- [x] [maximum_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_sphere.cl)
- [X] [maximum_x_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_x_projection.cl)
- [X] [maximum_y_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_y_projection.cl)
- [X] [maximum_z_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/maximum_z_projection.cl)
- [X] [mean_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mean_box.cl)
- [X] [mean_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mean_sphere.cl)
- [X] [mean_x_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mean_x_projection.cl)
- [X] [mean_y_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mean_y_projection.cl)
- [X] [mean_z_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/mean_z_projection.cl)
- [x] [median_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/median_box.cl)
- [x] [median_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/median_sphere.cl)
- [X] [minimum_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_box.cl)
- [ ] [minimum_distance_of_touching_neighbors](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_distance_of_touching_neighbors.cl) :question:
- [x] [minimum_image_and_scalar](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_image_and_scalar.cl)
- [x] [minimum_images](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_images.cl)
- [x] [minimum_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_sphere.cl)
- [X] [minimum_x_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_x_projection.cl)
- [X] [minimum_y_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_y_projection.cl)
- [X] [minimum_z_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/minimum_z_projection.cl)
- [x] [modulo_images](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/modulo_images.cl)
- [x] [multiply_image_and_coordinate](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/multiply_image_and_coordinate.cl)
- [x] [multiply_image_and_scalar](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/multiply_image_and_scalar.cl)
- [X] [multiply_images](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/multiply_images.cl)
- [x] [multiply_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/multiply_matrix.cl)
- [ ] [n_closest_points](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/n_closest_points.cl) :question:
- [x] [nan_to_num](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/nan_to_num.cl)
- [x] [nonzero_maximum_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/nonzero_maximum_box.cl)
- [x] [nonzero_maximum_diamond](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/nonzero_maximum_diamond.cl)
- [X] [nonzero_minimum_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/nonzero_minimum_box.cl)
- [x] [nonzero_minimum_diamond](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/nonzero_minimum_diamond.cl)
- [X] [not_equal](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/not_equal.cl)
- [X] [not_equal_constant](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/not_equal_constant.cl)
- [X] [onlyzero_overwrite_maximum_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/onlyzero_overwrite_maximum_box.cl)
- [X] [onlyzero_overwrite_maximum_diamond](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/onlyzero_overwrite_maximum_diamond.cl)
- [x] [paste](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/paste.cl)
- [ ] [point_index_list_to_mesh](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/point_index_list_to_mesh.cl) :question:
- [ ] [point_index_list_to_touch_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/point_index_list_to_touch_matrix.cl) :question:
- [x] [power](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/power.cl)
- [x] [power_images](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/power_images.cl)
- [x] [range](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/range.cl)
- [ ] [read_intensities_from_map](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/read_intensities_from_map.cl) :question:
- [x] [read_intensities_from_positions](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/read_intensities_from_positions.cl)
- [x] [reciprocal](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/reciprocal.cl)
- [X] [replace_intensities](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/replace_intensities.cl)
- [X] [replace_intensity](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/replace_intensity.cl)
- [ ] [resample](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/resample.cl) :exclamation:
- [X] [set](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set.cl)
- [X] [set_column](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_column.cl)
- [x] [set_image_borders](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_image_borders.cl)
- [X] [set_non_zero_pixels_to_pixel_index](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_non_zero_pixels_to_pixel_index.cl)
- [x] [set_plane](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_plane.cl)
- [x] [set_ramp_x](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_ramp_x.cl)
- [x] [set_ramp_y](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_ramp_y.cl)
- [x] [set_ramp_z](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_ramp_z.cl)
- [x] [set_row](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_row.cl)
- [x] [set_where_x_equals_y](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_where_x_equals_y.cl)
- [x] [set_where_x_greater_than_y](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_where_x_greater_than_y.cl)
- [x] [set_where_x_smaller_than_y](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/set_where_x_smaller_than_y.cl)
- [x] [sign](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/sign.cl)
- [X] [smaller](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/smaller.cl)
- [X] [smaller_constant](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/smaller_constant.cl)
- [X] [smaller_or_equal](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/smaller_or_equal.cl)
- [X] [smaller_or_equal_constant](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/smaller_or_equal_constant.cl)
- [X] [sobel](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/sobel.cl)
- [x] [square_root](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/square_root.cl)
- [x] [standard_deviation_z_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/standard_deviation_z_projection.cl)
- [X] [subtract_image_from_scalar](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/subtract_image_from_scalar.cl)
- [X] [sum_x_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/sum_x_projection.cl)
- [X] [sum_y_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/sum_y_projection.cl)
- [X] [sum_z_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/sum_z_projection.cl)
- [x] [touch_matrix_to_mesh](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/touch_matrix_to_mesh.cl)
- [x] [transpose_xy](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/transpose_xy.cl)
- [x] [transpose_xz](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/transpose_xz.cl)
- [x] [transpose_yz](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/transpose_yz.cl)
- [x] [undefined_to_zero](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/undefined_to_zero.cl)
- [x] [variance_box](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/variance_box.cl)
- [x] [variance_sphere](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/variance_sphere.cl)

**Comment by StRigaud** [comment]
For good example for Tier 1 contributions, see the following PRs:
- #118
- #117 
- #113 

I will try to build up a documentation from these later on.

**Comment by StRigaud** [comment]
I have started a documentation on how to create new kernels to CLIc
- [doc: add_new_kernel](https://github.com/clEsperanto/CLIc_prototype/blob/master/docs/add_new_kernel/add_new_kernel.md)

**Comment by StRigaud** [comment]
Update of T1 implemented kernel list

__WARNING:__ some kernel have not been tested and/or are missing their test function

**Comment by StRigaud** [comment]
@haesleinhuepf can you have a look a the kernel not yet implemented in the list and tell me which one we still should implement and those we should not because out of scope?

Thanks :smiley:

**Comment by haesleinhuepf** [comment]
I think those would be useful:
* [ ] [count_touching_neighbors](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/count_touching_neighbors.cl)
* [ ] [generate_binary_overlap_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_binary_overlap_matrix.cl)
* [ ] [generate_distance_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_distance_matrix.cl)
* [ ] [generate_touch_matrix](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/generate_touch_matrix.cl)
* [ ] [standard_deviation_z_projection](https://github.com/clEsperanto/clij-opencl-kernels/tree/clesperanto_kernels/kernels/standard_deviation_z_projection.cl)

**Comment by StRigaud** [comment]
All 5 filters have been pushed (with tests), as well as the hessian eigenvalues filter.

**Comment by StRigaud** [comment]
closing for now
