### ISSUE TITLE
TODO: kernel implementation

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#33]
This list keep tracks of the implementation of kernel class with corresponding OpenCL files. It does not take account of more advance operation.  
If you want to implement some, pick one!  

- [x] absolute_2d_x.cl
- [x] absolute_3d_x.cl
- [x] add_image_and_scalar_2d_x.cl
- [x] add_image_and_scalar_3d_x.cl
- [x] add_images_weighted_2d_x.cl
- [x] add_images_weighted_3d_x.cl
- [ ] affine_transform_2d_interpolate_x.cl
- [ ] affine_transform_2d_x.cl
- [ ] affine_transform_3d_interpolate_x.cl
- [ ] affine_transform_3d_x.cl
- [ ] apply_vectorfield_2d_interpolate_x.cl
- [ ] apply_vectorfield_2d_x.cl
- [ ] apply_vectorfield_3d_interpolate_x.cl
- [ ] apply_vectorfield_3d_x.cl
- [ ] arg_maximum_z_projection_x.cl
- [ ] average_distance_of_n_far_off_distances_x.cl
- [ ] average_distance_of_n_shortest_distances_x.cl
- [ ] average_distance_of_touching_neighbors_x.cl
- [ ] binary_and_2d_x.cl
- [ ] binary_and_3d_x.cl
- [ ] binary_edge_detection_2d_x.cl
- [ ] binary_edge_detection_3d_x.cl
- [ ] binary_not_2d_x.cl
- [ ] binary_not_3d_x.cl
- [ ] binary_or_2d_x.cl
- [ ] binary_or_3d_x.cl
- [ ] binary_subtract_2d_x.cl
- [ ] binary_subtract_3d_x.cl
- [ ] binary_xor_2d_x.cl
- [ ] binary_xor_3d_x.cl
- [x] block_enumerate_x.cl
- [ ] convolve_2d_x.cl
- [ ] convolve_3d_x.cl
- [x] copy_2d_x.cl
- [x] copy_3d_x.cl
- [ ] copy_slice_from_3d_x.cl
- [ ] copy_slice_to_3d_x.cl
- [ ] count_non_zero_projection_3d_2d_x.cl
- [ ] count_nonzero_pixels_slice_by_slice_sphere_3d_x.cl
- [ ] count_nonzero_pixels_sphere_2d_x.cl
- [ ] count_nonzero_voxels_sphere_3d_x.cl
- [ ] count_touching_neighbors_x.cl
- [ ] crop_2d_x.cl
- [ ] crop_3d_x.cl
- [ ] depth_projection_interpolation_x.cl
- [ ] depth_projection_x.cl
- [ ] detect_label_edges_2d_x.cl
- [ ] detect_label_edges_3d_x.cl
- [x] detect_maxima_2d_x.cl
- [ ] detect_maxima_3d_slice_by_slice_x.cl
- [x] detect_maxima_3d_x.cl
- [ ] detect_minima_2d_x.cl
- [ ] detect_minima_3d_slice_by_slice_x.cl
- [ ] detect_minima_3d_x.cl
- [ ] dilate_box_2d_x.cl
- [ ] dilate_box_3d_x.cl
- [ ] dilate_box_slice_by_slice_3d_x.cl
- [x] dilate_sphere_2d_x.cl
- [x] dilate_sphere_3d_x.cl
- [ ] dilate_sphere_slice_by_slice_3d_x.cl
- [ ] distance_matrix_to_mesh_x.cl
- [ ] distancemap_localPositiveMinimum_box_2d_x.cl
- [ ] distancemap_localPositiveMinimum_box_3d_x.cl
- [ ] distancemap_localPositiveMinimum_diamond_2d_x.cl
- [ ] distancemap_localPositiveMinimum_diamond_3d_x.cl
- [ ] divide_images_2d_x.cl
- [ ] divide_images_3d_x.cl
- [ ] downsample_2d_x.cl
- [ ] downsample_3d_x.cl
- [ ] downsample_xy_by_half_median_3d_x.cl
- [ ] draw_box_2d_x.cl
- [ ] draw_box_3d_x.cl
- [ ] draw_sphere_2d_x.cl
- [ ] draw_sphere_3d_x.cl
- [ ] drawline_2d_x.cl
- [ ] drawline_3d_x.cl
- [ ] entropy_2d_x.cl
- [ ] entropy_3d_x.cl
- [x] equal_2d_x.cl
- [x] equal_3d_x.cl
- [x] equal_constant_2d_x.cl
- [x] equal_constant_3d_x.cl
- [ ] erode_box_2d_x.cl
- [ ] erode_box_3d_x.cl
- [ ] erode_box_slice_by_slice_3d_x.cl
- [x] erode_sphere_2d_x.cl
- [x] erode_sphere_3d_x.cl
- [ ] erode_sphere_slice_by_slice_3d_x.cl
- [ ] excludeLabelsOnEdges_3d_x.cl
- [ ] exclude_labels_on_surface_2d_x.cl
- [ ] exclude_labels_on_surface_3d_x.cl
- [ ] exclude_labels_sub_surface_2d_x.cl
- [ ] exclude_labels_sub_surface_3d_x.cl
- [ ] exponential_2d_x.cl
- [ ] exponential_3d_x.cl
- [x] flag_existing_labels_x.cl
- [ ] flip_2d_x.cl
- [ ] flip_3d_x.cl
- [ ] flood_fill_diamond_x.cl
- [x] gaussian_blur_separable_2d_x.cl
- [x] gaussian_blur_separable_3d_x.cl
- [ ] generate_binary_overlap_matrix_2d_x.cl
- [ ] generate_binary_overlap_matrix_3d_x.cl
- [ ] generate_distance_matrix_x.cl
- [ ] generate_touch_matrix_2d_x.cl
- [ ] generate_touch_matrix_3d_x.cl
- [ ] gradient_x_2d_x.cl
- [ ] gradient_x_3d_x.cl
- [ ] gradient_y_2d_x.cl
- [ ] gradient_y_3d_x.cl
- [ ] gradient_z_3d_x.cl
- [x] greater_2d_x.cl
- [x] greater_3d_x.cl
- [x] greater_constant_2d_x.cl
- [x] greater_constant_3d_x.cl
- [x] greater_or_equal_2d_x.cl
- [x] greater_or_equal_3d_x.cl
- [x] greater_or_equal_constant_2d_x.cl
- [x] greater_or_equal_constant_3d_x.cl
- [ ] histogram_2d_x.cl
- [ ] histogram_3d_x.cl
- [ ] label_spots_in_x.cl
- [ ] labelled_spots_to_point_list_x.cl
- [ ] laplace_box_2d_x.cl
- [ ] laplace_box_3d_x.cl
- [ ] laplace_diamond_2d_x.cl
- [ ] laplace_diamond_3d_x.cl
- [ ] logarithm_2d_x.cl
- [ ] logarithm_3d_x.cl
- [ ] mask_2d_x.cl
- [ ] mask_3d_x.cl
- [ ] mask_label_2d_x.cl
- [ ] mask_label_3d_x.cl
- [ ] mask_stack_with_plane_3d_x.cl
- [ ] matrix_multiply_float_buffer.cl
- [ ] maximum_image_and_scalar_2d_x.cl
- [ ] maximum_image_and_scalar_3d_x.cl
- [ ] maximum_images_2d_x.cl
- [ ] maximum_images_3d_x.cl
- [ ] maximum_octagon_box_2d_x.cl
- [ ] maximum_octagon_box_3d_x.cl
- [ ] maximum_octagon_diamond_2d_x.cl
- [ ] maximum_octagon_diamond_3d_x.cl
- [ ] maximum_of_masked_pixels_3d_2d_x.cl
- [ ] maximum_of_touching_neighbors_x.cl
- [ ] maximum_projection_3d_2d_x.cl
- [x] maximum_separable_2d_x.cl
- [x] maximum_separable_3d_x.cl
- [ ] maximum_slice_by_slice_sphere_3d_x.cl
- [ ] maximum_sphere_2d_x.cl
- [ ] maximum_sphere_3d_x.cl
- [x] maximum_x_projection_x.cl
- [x] maximum_y_projection_x.cl
- [ ] maximum_z_projection_bounded_3d_2d_x.cl
- [x] maximum_z_projection_x.cl
- [ ] mean_of_touching_neighbors_x.cl
- [x] mean_separable_2d_x.cl
- [x] mean_separable_3d_x.cl
- [ ] mean_slice_by_slice_sphere_3d_x.cl
- [x] mean_sphere_2d_x.cl
- [x] mean_sphere_3d_x.cl
- [ ] mean_x_projection_x.cl
- [ ] mean_y_projection_x.cl
- [ ] mean_z_projection_bounded_3d_2d_x.cl
- [ ] mean_z_projection_x.cl
- [ ] median_box_2d_x.cl
- [ ] median_box_3d_x.cl
- [ ] median_of_touching_neighbors_x.cl
- [ ] median_slice_by_slice_box_3d_x.cl
- [ ] median_slice_by_slice_sphere_3d_x.cl
- [ ] median_sphere_2d_x.cl
- [ ] median_sphere_3d_x.cl
- [ ] median_z_projection_x.cl
- [ ] minimum_distance_of_touching_neighbors_x.cl
- [ ] minimum_image_and_scalar_2d_x.cl
- [ ] minimum_image_and_scalar_3d_x.cl
- [ ] minimum_images_2d_x.cl
- [ ] minimum_images_3d_x.cl
- [ ] minimum_octagon_box_2d_x.cl
- [ ] minimum_octagon_box_3d_x.cl
- [ ] minimum_octagon_diamond_2d_x.cl
- [ ] minimum_octagon_diamond_3d_x.cl
- [ ] minimum_of_masked_pixels_3d_2d_x.cl
- [ ] minimum_of_touching_neighbors_x.cl
- [ ] minimum_projection_3d_2d_x.cl
- [x] minimum_separable_2d_x.cl
- [x] minimum_separable_3d_x.cl
- [ ] minimum_slice_by_slice_sphere_3d_x.cl
- [ ] minimum_sphere_2d_x.cl
- [ ] minimum_sphere_3d_x.cl
- [x] minimum_x_projection_x.cl
- [x] minimum_y_projection_x.cl
- [ ] minimum_z_projection_bounded_3d_2d_x.cl
- [ ] minimum_z_projection_thresholded_bounded_3d_2d_x.cl
- [x] minimum_z_projection_x.cl
- [ ] multiply_image_and_coordinate_2d_x.cl
- [ ] multiply_image_and_coordinate_3d_x.cl
- [ ] multiply_image_and_scalar_2d_x.cl
- [ ] multiply_image_and_scalar_3d_x.cl
- [ ] multiply_images_2d_x.cl
- [ ] multiply_images_3d_x.cl
- [ ] multiply_matrix_x.cl
- [ ] multiply_stack_with_plane_3d_x.cl
- [ ] multiply_stack_with_scalars_x.cl
- [ ] n_shortest_distances_x.cl
- [ ] n_shortest_points_x.cl
- [ ] nonzero_maximum_box_2d_x.cl
- [ ] nonzero_maximum_box_3d_x.cl
- [ ] nonzero_maximum_diamond_2d_x.cl
- [ ] nonzero_maximum_diamond_3d_x.cl
- [x] nonzero_minimum_box_2d_x.cl
- [x] nonzero_minimum_box_3d_x.cl
- [ ] nonzero_minimum_diamond_2d_x.cl
- [ ] nonzero_minimum_diamond_3d_x.cl
- [x] not_equal_2d_x.cl
- [x] not_equal_3d_x.cl
- [x] not_equal_constant_2d_x.cl
- [x] not_equal_constant_3d_x.cl
- [ ] onlyzero_overwrite_maximum_box_2d_x.cl
- [ ] onlyzero_overwrite_maximum_box_3d_x.cl
- [ ] onlyzero_overwrite_maximum_diamond_2d_x.cl
- [ ] onlyzero_overwrite_maximum_diamond_3d_x.cl
- [ ] paste_2d_x.cl
- [ ] paste_3d_x.cl
- [ ] piv.cl
- [ ] pointindexlist_to_mesh_3d_x.cl
- [ ] power_2d_x.cl
- [ ] power_3d_x.cl
- [ ] power_images_2d_x.cl
- [ ] power_images_3d_x.cl
- [x] replace_intensities_x.cl
- [x] replace_intensity_x.cl
- [ ] replace_pixels_if_zero_x.cl
- [ ] reslice_bottom_3d_x.cl
- [ ] reslice_left_3d_x.cl
- [ ] reslice_radial_interpolate_2d_x.cl
- [ ] reslice_radial_interpolate_3d_x.cl
- [ ] reslice_right_3d_x.cl
- [ ] reslice_top_3d_x.cl
- [ ] rotate_clockwise_2d_x.cl
- [ ] rotate_clockwise_3d_x.cl
- [ ] rotate_counter_clockwise_2d_x.cl
- [ ] rotate_counter_clockwise_3d_x.cl
- [x] set_2d_x.cl
- [x] set_3d_x.cl
- [x] set_column_2d_x.cl
- [x] set_column_3d_x.cl
- [ ] set_image_borders_2d_x.cl
- [ ] set_image_borders_3d_x.cl
- [x] set_nonzero_pixels_to_pixelindex_x.cl
- [ ] set_plane_2d_x.cl
- [ ] set_plane_3d_x.cl
- [ ] set_ramp_x_2d_x.cl
- [ ] set_ramp_x_3d_x.cl
- [ ] set_ramp_y_2d_x.cl
- [ ] set_ramp_y_3d_x.cl
- [ ] set_ramp_z_2d_x.cl
- [ ] set_ramp_z_3d_x.cl
- [ ] set_row_2d_x.cl
- [ ] set_row_3d_x.cl
- [ ] set_where_x_equals_y_2d_x.cl
- [ ] set_where_x_equals_y_3d_x.cl
- [ ] set_where_x_greater_than_y_2d_x.cl
- [ ] set_where_x_greater_than_y_3d_x.cl
- [ ] set_where_x_smaller_than_y_2d_x.cl
- [ ] set_where_x_smaller_than_y_3d_x.cl
- [x] smaller_2d_x.cl
- [x] smaller_3d_x.cl
- [x] smaller_constant_2d_x.cl
- [x] smaller_constant_3d_x.cl
- [x] smaller_or_equal_2d_x.cl
- [x] smaller_or_equal_3d_x.cl
- [x] smaller_or_equal_constant_2d_x.cl
- [x] smaller_or_equal_constant_3d_x.cl
- [x] sobel_2d_x.cl
- [x] sobel_3d_x.cl
- [ ] standard_deviation_of_touching_neighbors_x.cl
- [ ] standard_deviation_z_projection_x.cl
- [ ] subtract_image_from_scalar_2d_x.cl
- [ ] subtract_image_from_scalar_3d_x.cl
- [x] sum_reduction_x.cl
- [x] sum_x_projection_x.cl
- [x] sum_y_projection_x.cl
- [x] sum_z_projection_x.cl
- [ ] touch_matrix_to_mesh_3d_x.cl
- [ ] transpose_xy_3d_x.cl
- [ ] transpose_xz_3d_x.cl
- [ ] transpose_yz_3d_x.cl
- [ ] undefined_to_zero_x.cl
- [ ] variance_2d_x.cl
- [ ] variance_masked_projection_x.cl
- [ ] variance_projection_x.cl
- [ ] watershed_binarize_labelmap_2d_x.cl
- [ ] watershed_binarize_labelmap_3d_x.cl
- [ ] watershed_detect_maxima_region_box_2d.cl
- [ ] watershed_detect_maxima_region_box_3d.cl
- [ ] watershed_eliminate_wrong_maxima_2d_x.cl
- [ ] watershed_eliminate_wrong_maxima_3d_x.cl
- [ ] watershed_local_maximum_2d_x.cl
- [ ] watershed_local_maximum_3d_x.cl
- [ ] write_values_to_positions_2d_x.cl
- [ ] write_values_to_positions_3d_x.cl

**Comment by StRigaud** [comment]
This needs to be updated accordingly to the new clEsperanto kernels

**Comment by haesleinhuepf** [comment]
Shall we maybe have one list with two checkboxes instead of two hard-to-sychronize lists?

**Comment by StRigaud** [comment]
closing the issue as the list is not up to date anymore.
